### ISSUE TITLE
hi , Mr gcobos,can you help me ,anyway thank you

### ISSUE THREAD

**Issue by mvwtest** [gcobos/grblesp#10]
in platformIO ,i buildin it,  
this error like loved me, but i don`t.
please get me a  way, thank U.

=================================================================================
*** [.pio\build\esp12e\lib8e3\grbl\nuts_bolts.cpp.o] Error 1
================================== [FAILED] Took 120.05 seconds ==================================The terminal process "C:\Users\M\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
=================================================================================

**Comment by mvwtest** [comment]
and  Vscodium + platform on Win10,
or linux suport only

**Comment by gcobos** [comment]
Googling around I found this. https://stackoverflow.com/questions/47946868/how-to-get-rid-of-terminal-will-be-reused-by-tasks-press-any-key-to-close-it

**Comment by mvwtest** [comment]
hi gcobos 
thank you commented.
my ? is :

[.pio\build\esp12e\lib8e3\grbl\nuts_bolts.cpp.o] Error 1

not orther,thanks again

**Comment by gcobos** [comment]
This is now fixed in main branch. Closing.
