### ISSUE TITLE
Soft WDT reset when sending "?" or "x1y1z1" commands

### ISSUE THREAD

**Issue by apollo2030** [gcobos/grblesp#4]
After compiling and flashing grblesp to the NodeMcu board once the `?` is sent via the serial monitor the board responds with the status string then it software resets. 

The same thing happens once a command lile `x1y1z1` is sent to the board. In this case only the `x1` motion is executed followed by a software reset.

While sending the `$` or `$#` commands no reset is happening.

**Comment by gcobos** [comment]
I removed my ".platformio" folder and suddenly I started having the same WDT problems, so merging. Thanks!
